repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files



-   repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'  # add version here
    hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      prargs: ["-f", "requirements.txt", "-o", "requirements.txt"]
